# Generated by Django 5.2.1 on 2025-05-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
