# Generated by Django 5.2.1 on 2025-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_quantity_alter_returnrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
